# Generated by Django 5.2.7 on 2025-11-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('topP', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llms.configuration')),
            ],
            options={
                'ordering': ['llm__name'],
            },
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('API_endpoint', models.URLField(blank=True, null=True)),
                ('API_key', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('configurations', models.ManyToManyField(related_name='llms', through='llms.ConfiguredModel', to='llms.configuration')),
            ],
        ),
        migrations.AddField(
            model_name='configuredmodel',
            name='llm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llms.llm'),
        ),
        migrations.AlterUniqueTogether(
            name='configuredmodel',
            unique_together={('llm', 'configuration')},
        ),
    ]
