# Generated by Django 5.2.7 on 2026-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='API_key',
            field=models.TextField(),
        ),
    ]
