# Generated by Django 5.2.7 on 2025-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0002_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='Default Configuration', max_length=100),
        ),
    ]
