# Generated by Django 5.2.7 on 2025-11-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0003_configuration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='topP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
