# Generated by Django 5.2.7 on 2025-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0004_alter_configuration_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='numRuns',
        ),
        migrations.AddField(
            model_name='llm',
            name='configurations',
            field=models.ManyToManyField(blank=True, related_name='llms', to='llms.configuration'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
